# Gmail Photography Appointment Scheduler Configuration
# Specialized for Maternity, Baby, Smash Cake, and Birthday Photography
# Copy this file to config.yaml and customize for your business

# Business Information
business:
  name: "Your Baby Photography Studio"
  email: "your-email@example.com"
  phone: "+1-555-0123"
  website: "https://yourbabyphotography.com"
  address: "123 Photography St, City, State 12345"
  tax_id: "12-3456789"
  business_type: "LLC"  # LLC, Corporation, Sole Proprietorship, etc.
  specialties:
    - "Maternity Photography"
    - "Newborn Photography"
    - "Baby Milestone Sessions"
    - "Smash Cake Photography"
    - "Birthday Photography"
    - "Family Portraits"

# Google Calendar Settings
calendar:
  target_calendar_id: "primary"  # Use "primary" for main calendar or specific calendar ID
  timezone: "America/New_York"    # Your business timezone
  business_hours:
    start: "09:00"
    end: "17:00"
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

# Appointment Settings
appointments:
  default_duration: 60  # minutes
  buffer_time: 15       # minutes between appointments
  reminder_schedule:
    - weeks: 2          # 2 weeks before
    - weeks: 1          # 1 week before
    - days: 3           # 3 days before
    - days: 2           # 2 days before
    - days: 1           # 1 day before
  
  # Specialized Session Types and Pricing for Baby Photography
  session_types:
    # Maternity Sessions
    maternity:
      name: "Maternity Session"
      duration: 90
      base_price: 250.00
      description: "Beautiful maternity photography session"
      recommended_weeks: "28-36"
      includes: ["30 edited images", "Online gallery", "Print release"]
    
    # Newborn Sessions
    newborn:
      name: "Newborn Session"
      duration: 180
      base_price: 350.00
      description: "Newborn photography within first 14 days"
      recommended_age: "5-14 days"
      includes: ["25 edited images", "Online gallery", "Print release", "Props included"]
    
    # Milestone Sessions
    milestone_3month:
      name: "3 Month Milestone"
      duration: 60
      base_price: 200.00
      description: "3 month baby milestone session"
      recommended_age: "12-16 weeks"
      includes: ["20 edited images", "Online gallery", "Print release"]
    
    milestone_6month:
      name: "6 Month Milestone"
      duration: 75
      base_price: 225.00
      description: "6 month baby milestone session"
      recommended_age: "24-28 weeks"
      includes: ["25 edited images", "Online gallery", "Print release"]
    
    milestone_9month:
      name: "9 Month Milestone"
      duration: 75
      base_price: 225.00
      description: "9 month baby milestone session"
      recommended_age: "36-40 weeks"
      includes: ["25 edited images", "Online gallery", "Print release"]
    
    milestone_1year:
      name: "1 Year Milestone"
      duration: 90
      base_price: 250.00
      description: "1 year birthday milestone session"
      recommended_age: "11-13 months"
      includes: ["30 edited images", "Online gallery", "Print release"]
    
    # Smash Cake Sessions
    smash_cake:
      name: "Smash Cake Session"
      duration: 90
      base_price: 275.00
      description: "1st birthday smash cake photography"
      recommended_age: "11-13 months"
      includes: ["30 edited images", "Online gallery", "Print release", "Cake included"]
    
    # Birthday Sessions
    birthday_session:
      name: "Birthday Photography"
      duration: 60
      base_price: 200.00
      description: "Birthday celebration photography"
      includes: ["25 edited images", "Online gallery", "Print release"]
    
    # Family Sessions
    family_portrait:
      name: "Family Portrait"
      duration: 90
      base_price: 300.00
      description: "Family portrait session"
      includes: ["35 edited images", "Online gallery", "Print release"]
    
    # Mini Sessions
    mini_session:
      name: "Mini Session"
      duration: 30
      base_price: 125.00
      description: "Quick 30-minute session"
      includes: ["15 edited images", "Online gallery", "Print release"]
    
    # Package Deals
    milestone_package:
      name: "Milestone Package (3, 6, 9, 12 months)"
      duration: 0  # Multiple sessions
      base_price: 800.00
      description: "Complete first year milestone package"
      includes: ["4 milestone sessions", "100+ edited images", "Online galleries", "Print releases", "10% discount"]
    
    newborn_package:
      name: "Newborn + Milestone Package"
      duration: 0  # Multiple sessions
      base_price: 1100.00
      description: "Newborn + 3 milestone sessions"
      includes: ["Newborn session", "3 milestone sessions", "125+ edited images", "Online galleries", "Print releases", "15% discount"]

# Baby Photography Specific Settings
baby_photography:
  # Milestone Tracking
  milestones:
    enabled: true
    auto_reminders: true
    reminder_days_before: 30
    
    # Milestone Ages (in days)
    milestone_ages:
      newborn: 14
      three_month: 90
      six_month: 180
      nine_month: 270
      one_year: 365
      eighteen_month: 730
      two_year: 1095
  
  # Newborn Session Settings
  newborn:
    max_age_days: 14
    preferred_age_days: "5-10"
    requires_consultation: true
    props_included: true
    backup_dates: true  # Allow rescheduling for baby's mood
  
  # Smash Cake Settings
  smash_cake:
    cake_included: true
    cake_flavors: ["Vanilla", "Chocolate", "Strawberry", "Red Velvet"]
    cake_designs: ["Simple", "Decorated", "Themed", "Custom"]
    props_included: true
    cleanup_service: true
  
  # Birthday Session Settings
  birthday:
    themes_available:
      - "Princess"
      - "Superhero"
      - "Farm"
      - "Space"
      - "Ocean"
      - "Jungle"
      - "Sports"
      - "Custom"
    
    colors_available:
      - "Pink"
      - "Blue"
      - "Purple"
      - "Green"
      - "Yellow"
      - "Orange"
      - "Red"
      - "Rainbow"
      - "Neutral"
    
    props_available:
      - "Balloons"
      - "Banners"
      - "Crowns"
      - "Tiaras"
      - "Capes"
      - "Hats"
      - "Stuffed Animals"
      - "Books"
      - "Musical Instruments"

# CRM Settings
crm:
  # Client Management
  default_tags:
    - "New Client"
    - "VIP"
    - "Returning Client"
    - "Referral"
    - "Maternity Client"
    - "Newborn Client"
    - "Milestone Client"
    - "Birthday Client"
    - "Smash Cake Client"
    - "Family Client"
    - "Package Client"
  
  # Referral Sources
  referral_sources:
    - "Google Search"
    - "Social Media"
    - "Word of Mouth"
    - "Facebook Groups"
    - "Instagram"
    - "Pinterest"
    - "Local Moms Groups"
    - "Pediatrician Referral"
    - "Hospital Referral"
    - "Daycare Referral"
    - "Referral Program"
    - "Other"
  
  # Budget Ranges
  budget_ranges:
    - "$100-250"
    - "$250-500"
    - "$500-1000"
    - "$1000-2000"
    - "$2000+"
  
  # Project Types
  project_types:
    - "Maternity"
    - "Newborn"
    - "Milestone"
    - "Birthday"
    - "Smash Cake"
    - "Family Portrait"
    - "Package Deal"
    - "Other"
  
  # Family Types
  family_types:
    - "Expecting"
    - "Newborn"
    - "Baby (0-1 year)"
    - "Toddler (1-3 years)"
    - "Multiple Children"
    - "Adoption"
    - "Surrogacy"
    - "Other"
  
  # Photography Experience Levels
  experience_levels:
    - "First Time"
    - "Some Experience"
    - "Experienced"
    - "Professional"
    - "Other"
  
  # Follow-up Settings
  follow_up:
    enabled: true
    default_delay_days: 3
    reminder_frequency: "daily"  # daily, weekly, monthly
    
    # Special follow-up triggers
    triggers:
      - "After maternity session"
      - "Before newborn session"
      - "Milestone reminders"
      - "Birthday session planning"
      - "Package completion"
      - "Gallery delivery"
  
  # Marketing Settings
  marketing:
    email_campaigns_enabled: true
    social_media_integration: true
    referral_program_enabled: true
    referral_bonus: 50.00  # Amount for successful referrals
    
    # Special marketing campaigns
    campaigns:
      - "Maternity Announcement"
      - "Newborn Welcome"
      - "Milestone Reminders"
      - "Birthday Planning"
      - "Holiday Specials"
      - "Seasonal Promotions"

# Email Templates
email:
  from_name: "Your Baby Photography Studio"
  reply_to: "your-email@example.com"
  templates:
    confirmation: "templates/confirmation.html"
    reminder_2weeks: "templates/reminder_2weeks.html"
    reminder_1week: "templates/reminder_1week.html"
    reminder_3days: "templates/reminder_3days.html"
    reminder_2days: "templates/reminder_2days.html"
    reminder_1day: "templates/reminder_1day.html"
    follow_up: "templates/follow_up.html"
    thank_you: "templates/thank_you.html"
    referral_request: "templates/referral_request.html"
    
    # Specialized templates for baby photography
    maternity_reminder: "templates/maternity_reminder.html"
    newborn_prep: "templates/newborn_prep.html"
    milestone_reminder: "templates/milestone_reminder.html"
    birthday_planning: "templates/birthday_planning.html"
    smash_cake_prep: "templates/smash_cake_prep.html"
    gallery_ready: "templates/gallery_ready.html"

# Gmail Settings
gmail:
  label_name: "Baby Photography Appointments"
  search_query: "subject:(appointment OR session OR photoshoot OR maternity OR newborn OR milestone OR birthday) OR body:(appointment OR session OR photoshoot OR maternity OR newborn OR milestone OR birthday)"

# Database Settings
database:
  type: "sqlite"  # sqlite, postgresql, mysql
  path: "data/crm.db"
  backup_enabled: true
  backup_frequency: "daily"  # daily, weekly, monthly
  backup_retention: 30  # days

# Logging
logging:
  level: "INFO"
  file: "logs/appointments.log"
  max_size: "10MB"
  backup_count: 5
  
  # Separate CRM logging
  crm_log_file: "logs/crm.log"
  crm_log_level: "INFO"

# Reporting and Analytics
analytics:
  enabled: true
  dashboard_enabled: true
  export_formats: ["csv", "pdf", "json"]
  scheduled_reports: true
  report_frequency: "weekly"  # daily, weekly, monthly, quarterly
  
  # Key Performance Indicators for Baby Photography
  kpis:
    - "Total Revenue"
    - "New Clients per Month"
    - "Client Retention Rate"
    - "Average Session Value"
    - "Referral Rate"
    - "Customer Lifetime Value"
    - "Appointment Conversion Rate"
    - "Milestone Package Sales"
    - "Newborn Session Bookings"
    - "Birthday Session Bookings"
    - "Smash Cake Session Bookings"
    - "Package Deal Conversion Rate"
