#!/bin/bash

echo "🌐 Cloudflare Dashboard Configuration Guide"
echo "==========================================="
echo ""
echo "Since command line configuration is having issues, let's use the dashboard:"
echo ""
echo "1. Go to: https://dash.cloudflare.com/"
echo ""
echo "2. Click on 'Zero Trust' in the left sidebar"
echo ""
echo "3. Click on 'Access' → 'Tunnels'"
echo ""
echo "4. Find your tunnel: 'snapstudio-tunnel'"
echo "   (ID: 6413ac9d-3106-4f64-8a71-6b5ea1d66cca)"
echo ""
echo "5. Click 'Configure' button next to your tunnel"
echo ""
echo "6. In the 'Public Hostnames' section:"
echo "   - Click 'Add a public hostname' (or edit existing)"
echo "   - Subdomain: @ (or leave blank for root domain)"
echo "   - Domain: snapstudio.cc"
echo "   - Service: http://localhost:5001"
echo "   - Click 'Save hostname'"
echo ""
echo "7. Start the tunnel with token:"
echo "   cloudflared tunnel run --token YOUR_TOKEN"
echo ""
echo "Current status:"
echo "✅ Container: $(podman ps | grep snapstudio-app > /dev/null && echo 'Running' || echo 'Not running')"
echo "❌ Tunnel: Not running (needs dashboard configuration)"
echo ""
echo "Once you configure the hostname in the dashboard, run:"
echo "cloudflared tunnel run --token eyJhIjoiNDk2NDI1ZjViYTJjOTM0ZmUyZDJlYmNmNTZhMjU4Y2IiLCJ0IjoiNjQxM2FjOWQtMzEwNi00ZjY0LThhNzEtNmI1ZWExZDY2Y2NhIiwicyI6Ik5XTTVNV1JqWm1VdFlqWTNOQzAwWkdZd0xUa3daVFl0TUdRek9EUTFPVGxtTmpGayJ9"
