#!/bin/bash

echo "🔧 SnapStudio Tunnel Configuration Helper"
echo "========================================="
echo ""
echo "The tunnel is running but getting 522 errors. This usually means:"
echo "1. The tunnel is configured to point to the wrong service"
echo "2. The service URL in Cloudflare dashboard is incorrect"
echo ""
echo "Let's fix this:"
echo ""
echo "1. Go to Cloudflare Dashboard:"
echo "   https://dash.cloudflare.com/"
echo ""
echo "2. Navigate to: Zero Trust → Access → Tunnels"
echo ""
echo "3. Find your tunnel (ID: 6413ac9d-3106-4f64-8a71-6b5ea1d66cca)"
echo ""
echo "4. Click 'Configure' → 'Public Hostnames'"
echo ""
echo "5. Make sure the configuration is:"
echo "   - Subdomain: @ (or snapstudio)"
echo "   - Domain: snapstudio.cc"
echo "   - Service: http://localhost:5001"
echo ""
echo "6. Save the configuration"
echo ""
echo "7. Test the connection:"
echo "   curl https://snapstudio.cc/health"
echo ""
echo "Current Status:"
echo "✅ Container: Running on localhost:5001"
echo "✅ Tunnel: Running (PID: $(pgrep cloudflared))"
echo "❌ Connection: 522 error (needs configuration fix)"
echo ""
echo "Alternative: Create a new tunnel with correct configuration"
echo "1. Delete the current tunnel"
echo "2. Create a new tunnel"
echo "3. Configure it properly from the start"
