#!/bin/bash

echo "🔧 Cloudflare Tunnel Configuration Commands"
echo "==========================================="
echo ""
echo "Option 1: Use Cloudflare Dashboard (Recommended)"
echo "1. Go to: https://dash.cloudflare.com/"
echo "2. Zero Trust → Access → Tunnels"
echo "3. Find tunnel: snapstudio-tunnel"
echo "4. Configure → Public Hostnames"
echo "5. Set Service: http://localhost:5001"
echo ""
echo "Option 2: Command Line Configuration"
echo "1. Create tunnel config file:"
echo ""
echo "cat > ~/.cloudflared/config.yml << EOF"
echo "tunnel: 6413ac9d-3106-4f64-8a71-6b5ea1d66cca"
echo "credentials-file: ~/.cloudflared/6413ac9d-3106-4f64-8a71-6b5ea1d66cca.json"
echo ""
echo "ingress:"
echo "  - hostname: snapstudio.cc"
echo "    service: http://localhost:5001"
echo "  - hostname: www.snapstudio.cc"
echo "    service: http://localhost:5001"
echo "  - service: http_status:404"
echo "EOF"
echo ""
echo "2. Run tunnel with config:"
echo "cloudflared tunnel run --config ~/.cloudflared/config.yml"
echo ""
echo "Current tunnel status:"
echo "✅ Tunnel running: $(pgrep cloudflared > /dev/null && echo 'Yes' || echo 'No')"
echo "✅ Container running: $(podman ps | grep snapstudio-app > /dev/null && echo 'Yes' || echo 'No')"
echo "❌ Public access: 522 error (needs configuration)"
